# Use a special RP
resource_pack: halloween

# Use a different RP when combined with other configs
add_resource_pack: all

# Alternate resource packs can be accessed with /getrp <pack>
alternate_resource_packs:
  halloween:
    url: "https://download.mc-packs.net/pack/597e35b3b13bc930521dcf9dfd162ce755bb9d8f.zip"